### ISSUE TITLE
是否考虑兼容Windows？

### ISSUE THREAD

**Issue by amao12580** [BrikerMan/HTML-table-convert-to-markdown-table#1]
遗憾HTML2Markdown只能在MAC系统运行，不知道是否有兼容Windows的计划呢？

**Comment by BrikerMan** [comment]
@amao12580 一直以为是极少用户的需求，如果有需要的话，可以写个网页版。

**Comment by amao12580** [comment]
@BrikerMan 兼容linux也行，网页版哪来的用户流量呢？

**Comment by BrikerMan** [comment]
@amao12580 然而做网页版难度对于我远远低于做linux，windows版本

**Comment by BrikerMan** [comment]
@amao12580 直接放在我自己的vps即可。

**Comment by BrikerMan** [comment]
@amao12580 弄了个网页版，http://html2markdown.eliyar.biz/ ，试试看。

**Comment by amao12580** [comment]
@BrikerMan 网页版不能正常工作。
示例html片段为：
[html.txt](https://github.com/BrikerMan/HTML-table-convert-to-markdown-table/files/334603/html.txt)

**Comment by amao12580** [comment]
![screen](https://cloud.githubusercontent.com/assets/4270177/16376684/2af6e914-3c94-11e6-8209-90d0bd2b8c80.png)

**Comment by BrikerMan** [comment]
这个表格式不太对呀，不应该这样么

<table class="pure-table pure-table-horizontal">
    <thead>
        <tr>
            <th>#</th>
            <th>Make</th>
            <th>Model</th>
            <th>Year</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>1</td>
            <td>Honda</td>
            <td>Accord</td>
            <td>2009</td>
        </tr>

        <tr>
            <td>2</td>
            <td>Toyota</td>
            <td>Camry</td>
            <td>2012</td>
        </tr>

        <tr>
            <td>3</td>
            <td>Hyundai</td>
            <td>Elantra</td>
            <td>2010</td>
        </tr>
    </tbody>
</table>


Steven Cheng <notifications@github.com>于2016年6月27日周一 下午6:23写道：

**Comment by amao12580** [comment]
@BrikerMan 确实不太符合标准，缺失thead/tbody/tfoot标签。有时间做一下程序容错吗？

**Comment by BrikerMan** [comment]
晚上做一下那么。

Steven Cheng <notifications@github.com>于2016年6月28日周二 下午2:37写道：

**Comment by amao12580** [comment]
Waiting for you

**Comment by BrikerMan** [comment]
@amao12580 done.
